apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: service-a-monitor
  labels:
    release: prometheus-stack  # Must match the Prometheus release name
spec:
  selector:
    matchLabels:
      app: service-a
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - default
